name: arpa_weather
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.*
  - geopandas=0.12.*
  - matplotlib
  - pandas= 1.5.3
  - dask=2023.3.*
  - ipywidgets=8.0.*
  - seaborn=0.12.*
  - plotly=5.9.*
  - pip=22.3.*
  - pip:
    - sodapy==2.2.0