name: arpa_weather
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.*
  - geopandas=0.12.*
  - matplotlib
  - pandas= .5.3
  - dask=2023.3.*
  - ipywidgets=8.0.*
  - pip=22.3.*
  - pip:
    - sodapy==2.2.0